version: '3'
services:
  app:
    build: .
    command: bundle exec ruby lib/app.rb -o 0.0.0.0
    ports:
      - "4567:4567"
    volumes:
      - .:/app:cached
      - /app/vendor
    depends_on:
      - db
    tty: true
    stdin_open: true

  front:
    build: front
    volumes:
      - ./front:/app/front:cached
      - /app/front/node_modules
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
